<?php

    require_once '../App/ValidaLogin.php';

    $idEvento = $_POST['criar_atividade'];

?>

<div class="align-title"><h1 class="title">Criar Atividade</h1></div>
<aside class="menu-topo">
    <nav class="menu">
        <a href="/index_evento"><img src="./img/icons/eventos.png">Áreas Profissionais</a>
        <a href="/sair" class="sair">Sair</a>
    </nav>
</aside>

<section class="grid-base">
    <main class="content">

    <div class="form-align">
        <form action="/cadastrar_atividade" method="post" class="form-register space-top">
            <div class="input-grande" style="display: none">
                <span>Id</span>
                <input type="text" name="id" maxlength="80" class="input-radius" value="<?= $idEvento ?>">
            </div>
            <div class="input-grande">
                <span>Tema</span>
                <input type="text" name="tema" maxlength="180" class="input-radius">
            </div>
            <div class="input-medio">
                <label>Hora</label>
                <input type="time" name="hora" class="input-radius">
            </div>
            <div class="input-medio">
                <label>Local</label>
                <input type="text" name="local" maxlength="120" class="input-radius">
            </div>
            <div class="input-grande">
                <label>Descrição</label>
                <textarea name="descricao" class="radius-textarea" rows="5" maxlength="180"></textarea>
            </div>
            <div class="input-grande">
                <button type="submit" class="btn-register btn-right btn-space-top">Adicionar</button>
                <a href="/index_evento" class="btn-link btn-confirm btn-right btn-space-top">Voltar</a>
            </div>
        </form>
    </div>

    </main>
</section>