<?php

    require_once '../App/ValidaLogin.php';

?>

<aside class="menu-topo">
    <nav class="menu">
        <a href="/criar_evento"><img src="./img/icons/criar-evento.png">Criar Área</a>
        <!--h1>Áreas Profissionais</h1-->
        <a href="/sair" class="sair">Sair</a>
    </nav>
</aside>

<section class="grid-base">
    <main class="content">
        <h1 class="title-center-align">Áreas Profissionais</h1>
        <hr>
        <section class="card">
            <?php foreach($this->view->eventos as $evento) { ?>
                <form action="/acao_evento" method="post" class="card-evento card-block">
                    <div class="card-img card-img-evento">
                        <img src="./img/evento.png" alt="evento">
                    </div>
                    <div class="body-card body-card-evento">
                        <h1><?= $evento['titulo'] ?></h1>
                        <div class="btn-card btn-card-evento">
                            <button type="submit" value="<?= $evento['id'] ?>" name="alterar" class="btn-warning-full">Alterar</button>
                            <button type="submit" value="<?= $evento['id'] ?>" name="criar_atividade" class="btn-register-full">Criar Atividade</button>
                        </div>
                        <div class="btn-card btn-card-evento">
                            <button type="submit" value="<?= $evento['id'] ?>" name="ver_atividades" class="btn-confirm-full">Ver Atividades</button>
                        </div>
                    </div>
                </form>
            <?php } ?>
        </section>
    </main>
</section>