<?php

    require_once '../App/ValidaLogin.php';
    //$idAtividade = $_POST['atividades'];

?>

<?php foreach($this->view->atividades as $atividade) { ?>
    <div class="align-title"><h1 class="title"> <?= $atividade['titulo'] ?> </h1></div>
<?php } ?>


<aside class="menu-topo">
    <nav class="menu">
        <a href="/index_evento"><img src="./img/icons/eventos.png">Áreas Profissionais</a>
        <a href="/sair" class="sair">Sair</a>
    </nav>
</aside>

<section class="grid-base">
    <main class="content">
        <section class="card">
            <?php foreach($this->view->atividades as $atividade) { ?>
                <form action="/acao_atividade" method="post" class="card-atividade card-block-column">

                    <div class="card-title">
                        <h1><?= $atividade['tipo'] ?></h1>
                        <hr>
                    </div>

                    <div class="card-block-row">
                        <div class="card-img card-img-atividade">
                            <img src="./img/<?= explode(" ", $atividade['tipo'])[0] ?>.png" alt="Tipo Atividade">
                        </div>

                        <div class="body-card body-card-atividade">
                            <div class="div-grande">Tema: <strong><?= $atividade['tema'] ?></strong></div>

                            <div class="div-grande">
                                <div class="div-media">Local: <strong><?= $atividade['local'] ?></strong></div>
                                <div class="div-pequena">Hora: <strong><?= $atividade['hora'] ?>h</strong></div>
                            </div>

                            <?php if($atividade['descricao'] != '') { ?>
                                <p><?= $atividade['descricao'] ?></p>
                            <?php } else { ?>
                                <br/>
                            <?php } ?>

                            <div class="btn-card btn-card-atividade">
                                <button type="submit" name="deletar" value="<?= $atividade['id'] ?>" class="btn-danger-full">Deletar</button>
                                <button type="submit" name="alterar" value="<?= $atividade['id'] ?>" class="btn-warning-full">Alterar</button>
                            </div>
                        </div>
                    </div>

                </form>
            <?php } ?>
        </section>
    </main>
</section>