<?php

    require_once '../App/ValidaLogin.php';

?>

<div class="align-title"><h1 class="title">Áreas Profissionais</h1></div>
<aside class="menu-topo">
    <nav class="menu">
        <a href="/criar_evento"><img src="./img/icons/criar-evento.png"><span style="color: #fff" class="esconder">Criar Área</span></a>
        <a href="/sair" class="sair">Sair</a>
    </nav>
</aside>

<section class="grid-base">
    <main class="content">
        <section class="card">
            <?php foreach($this->view->eventos as $evento) { ?>
                <form action="/acao_evento" method="post" class="card-evento card-block">
                    <div class="body-card body-card-evento">
                        <h1><?= $evento['nome'] ?></h1>
                        <div class="btn-card btn-card-evento">
                            <button type="submit" value="<?= $evento['id'] ?>" name="ver_atividades" class="btn-confirm-full">Ver Atividade</button>
                            <button type="submit" value="<?= $evento['id'] ?>" name="deletar" class="btn-danger-full">Deletar</button>
                            <button type="submit" value="<?= $evento['id'] ?>" name="criar_atividade" class="btn-register-full">Criar Atividade</button>
                        </div>
                    </div>
                </form>
            <?php } ?>
        </section>
    </main>
</section>