<body class="bg-img-cadastro">
    <header class="header-cadastro">
        <h1 class="font-titulo">Open Day</h1>
    </header>

    <main class="form-align">
        
        <form action="/cadastrar" method="post" class="form-register">
            <div class="input-grande">
                <span>Nome</span>
                <input type="text" name="nome" id="nome" class="input-radius"/>
                <span class="mensagem-erro erro-direita erro-nome"></span>
            </div>
            <div class="input-grande">
                <label>E-mail</label>
                <input type="text" name="email" class="input-radius">
            </div>
            <div class="input-grande">
                <label>Telefone</label>
                <input type="text" name="telefone" class="input-radius"/>
            </div>
            <div class="input-grande">
                <label>Escola</label>
                <input type="text" name="escola" class="input-radius">
            </div>
            <div class="input-grande">
                <label>Área de Interesse</label>
                <select name="area" class="input-radius">
                    <option value="">Selecione</option>
                    <option value="Engenharia">Engenharia</option>
                    <option value="Saúde">Saúde</option>
                    <option value="Gestão e Negócios">Gestão e Negócios</option>
                    <option value="Tecnologia">Tecnologia</option>
                    <option value="Artes, Comunicação e Design">Artes, Comunicação e Design</option>
                    <option value=Direito">Direito</option>
                    <option value="Gastronomia">Gastronomia</option>
                </select>
            </div>
                
            </div>
            <?php if(isset($_GET['cadastro']) == 'erro') { ?>
                <div class="msg-box msg-error">
                    <small class="text-error">Por favor, preencha todos os campos!</small>
                </div>
            <?php } ?>
            <div class="input-grande">
                <button type="submit" class="btn-register btn-right btn-space-top">Navegar</button>
            </div>
        </form>
    </main>

    <footer class="rodape">
        <img src="./img/logo_branca.png" alt="wyden">
        <h1>Sistema desenvolvido pela aluna <a href="https://beatrizsantiago.github.io/">@Beatriz Santiago</a></h1>
    </footer>
</body>