<header class="header">
    <h1>Open Day</h1>
    <!--hr-->
    <p>Seja bem-vindo(a)!</p>
</header>
<main class="content">
    <section class="card">
        <?php foreach($this->view->eventos as $evento) { ?>
            <a href="/lista_atividade?id=<?= $evento['id'] ?>" class="card-evento card-block" style="text-decoration: none; color: #000">
                <div class="body-card body-card-evento">
                    <h1><?= $evento['nome'] ?></h1>
                    <p><?= $evento['descricao'] ?></p>
                </div>
            </a>
        <?php } ?>
    </section>
</main>
