<body class="bg-img-cadastro">
    <header class="header">
        <h1 class="font-titulo">Open Day</h1>
        <!--hr-->
        <p style="color: #fff; padding: 0 8px">Seja bem-vindo(a)! Saiba mais sobre a sua área profissional desejada.</p>
    </header>
    <main class="content">
        <section class="card">
            <?php foreach($this->view->eventos as $evento) { ?>
                <a href="/lista_atividade?id=<?= $evento['id'] ?>" class="card-evento card-block" style="text-decoration: none; color: #000">
                    <div class="body-card body-card-evento">
                        <h1><?= $evento['nome'] ?></h1>
                        <p><?= $evento['descricao'] ?></p>
                    </div>
                </a>
            <?php } ?>
        </section>
    </main>

    <footer class="rodape">
        <img src="./img/logo_branca.png" alt="wyden">
        <h1>Sistema desenvolvido pela aluna <a href="https://beatrizsantiago.github.io/">@Beatriz Santiago</a></h1>
    </footer>
</body>
