<body class="bg-img">
    <div class="card-login">
        <h1 class="title-login">Login</h1>
        <form action="/autenticar" method="post">
            <div class="input-grande">
                <label>E-mail: </label>
                <input type="text" name="login" class="input-login">
            </div>
            <div>
                <label class="label-login">Senha:</label>
                <input type="password" name="senha" class="input-login">
            </div>
            <div class="btn-align-center btn-space-top">
                <a href="/area_profissional" class="btn-link btn-register btn-cadastro">Participante</a>
                <button type="submit" class="btn-confirm">Entrar</button>
            </div>

            <?php if($this->view->login == 'erro') { ?>
                <div class="msg-box msg-error">
                    <small class="text-error">E-mail e/ou senha invalido(s)!</small>
                </div>
            <?php } ?>
            
        </form>
    </div>
    <footer class="rodape-login">
        <img src="./img/logo_branca.png" alt="wyden">
        <h1>Sistema desenvolvido pela aluna <a href="https://beatrizsantiago.github.io/">@Beatriz Santiago</a></h1>
    </footer>
</body>